### ISSUE TITLE
Hover Event Unbound After Click

### ISSUE THREAD

**Issue by martindale** [JohnMcLear/ep_file_menu_toolbar#5]
One of our users is reporting that once a menu element is clicked, the hover event stops firing and the menu ceases to function completely.

Safari 9.01 on an OS X El Capitan (Ver. 10.11.1)

**Comment by JohnMcLear** [comment]
Also experience this on other browsers?

**Comment by JohnMcLear** [comment]
Unable to replicate.

**Comment by martindale** [comment]
This came from a user of write.roleplaygateway.com, but I suspect they've since moved on.  I don't have OSX (nor Safari), so am unable to test.  Thanks for following up. :+1:
